- name: Generate Prometheus config from template
  hosts: localhost
  tasks:
    - name: Render prometheus.yml
      template:
        src: prometheus.yml.j2
        dest: ./prometheus/prometheus.yml
